package huangwf5.utils;

public class IBceStatic {
	public final static  String BCE_ATTR_INSERT="insert into base.bce_attr (ATTR_ID, MODULE_ID, OBJ_NAME, ATTR_CODE, ATTR_NAME, I18N_RES, FIELD_TYPE, FIELD_WIDTH, COL_SPAN, IS_NULLABLE, FIELD_HEIGHT, IS_MULTIVALUEABLE, EDIT_TYPE, MAX_LENGTH, RES_SRC, RES_PARAM, DEFAULT_VALUE, MUTI_FLAG, VALUE_CLASS, RULE_ID, REMARKS, STATE, REGION_ID, EFF_TYPE)\n values(";
	public final static String BCE_FRAME_ATTR_INSERT="insert into base.bce_frame_attr (ATTR_ID, BCE_FRAME_ID, FORM_ID, MODULE_ID, GROUP_ID, IS_VISIBLE, IS_EDITABLE, FIELD_HEIGHT, FIELD_WIDTH, COL_SPAN, IS_NULLABLE, EDIT_TYPE, MAX_LENGTH, RES_SRC, RES_PARAM, DEFAULT_VALUE, VALUE_CLASS, IS_VALIDATE, SEQ_NO, IS_LOG, EXT_1, EXT_2, EXT_3, STATE, IS_MULTIVALUEABLE, ATTR_NAME, I18N_RES, MUTI_FLAG, REGION_ID, EFF_TYPE)\n values(";
	public final static String UP_ALL_NET_CONF_INSERT="insert into product.up_all_net_conf (SERIAL_ID, SERVICE_ID, PRODUCT_ITEM_ID, NAME, ITEM_TYPE, ALLNET_TYPE, ALLNET_CODE, PLAN_ID, NOTES, DEL_FLAG, FORMAT_STYLE, FORMAT_RULE, FEE_ATTACH, ICB_PARAM_VALUE)\n values (";
}
